### ISSUE TITLE
Can't connect to hacker-news.firebaseio.com API

### ISSUE THREAD

**Issue by rizkysyazuli** [dance2die/SHANc#490]
Hi,

I'm trying to use your `gatsby-node.js` in my own project, but I keep getting this error.

```
Error: getaddrinfo ENOTFOUND hacker-news.firebaseio.com
```

I tried cloning and running your repo. Same problem. Then I tried switching to `node-fetch` instead of `axios`. Basically getting the same error.

```
FetchError: request to https://hacker-news.firebaseio.com/v0/item/24354448.json failed  , reason: getaddrinfo ENOTFOUND hacker-news.firebaseio.com
```

I've pinged the host and curl-ed the link. Both work fine.
Maybe you have some ideas? I'm not really an expert in Node.

**Comment by rizkysyazuli** [comment]
I did a quick fix to limit the amount of `storyIds` being requested. This seems to fix the problem. 

```js
// gatsby-node.js - line 28
const storyIds = [
  ...new Set([
    ...topResults.data.slice(0, 100),
    ...newResults.data.slice(0, 100),
    ...bestResults.data.slice(0, 100)
  ]),
];
```

I guess Firebase doesn't like us fetching all 1500 (best, top, new) stories at once.

**Comment by dance2die** [comment]
Thank you for sharing the answer, @rizkysyazuli.

I am sorry for the late reply although 
I use this site daily but haven't touched the source/github for years :)
